# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4393b9d841290365d154f76c4dd3a4f788ac014d5b6fb56bf28d4ba892db9d371cf217156b836e1207636e8d5292048c3a69357476e48232aacbda041b67c320

test:
  secret_key_base: 3ac7dd87f59504b2d828f3a1b8ebe5e2d31ec5948a651738c0a8eb1f7645f695e7d1e16eeeb1e0978ad78180dc579870dcf0e368e070114a17ee1d8ed089c8af

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
